# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr=np.arange(0,21)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Creating sample array
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [5]:
len(arr)

18

In [6]:
arr[-1]

np.int64(95)

In [7]:
#Get a value at an index
arr[9]

np.int64(55)

In [8]:
#Get values in a range
arr[1:11:2]

array([15, 25, 35, 45, 55])

### Filtering

In [ ]:
import numpy as np

In [2]:
# Filtering condition

arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [3]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [4]:
arr2=np.array([True,True,False,False])

In [5]:
np.where(arr<100)

(array([0, 1, 3, 5, 6]),)

In [26]:
arr[5]

np.int64(18)

In [27]:
arr[2]

np.int64(1010)

In [28]:
np.where(arr<100)# where function outputs index location of values
# meeting the condition

(array([0, 1, 3, 5, 6]),)

In [30]:
arr[np.where(arr>100)]=10

In [18]:
arr

array([ 1,  2, 10,  4, 10, 18, 71, 10])

In [19]:
np.where(arr<100)

(array([0, 1, 2, 3, 4, 5, 6, 7]),)

In [20]:
np.where(arr==100)

(array([], dtype=int64),)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [ ]:
import numpy as np

In [6]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [ ]:
# syntex for 2d array indexing 
#[row,col],[row][col]

In [7]:
arr_2d[2][2]

np.int64(128)

In [ ]:
arr_2d[:,1]

array([ 2, 15, 96])

In [34]:
l1=[1,2,3,4,5]

In [35]:
l1[:3]

[1, 2, 3]

In [36]:
arr_2d[:2,:2]

array([[ 1,  2],
       [12, 15]])

In [37]:
arr3=np.arange(27).reshape(3,3,3)

In [ ]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr_2d[1:,:2]

array([[12, 15],
       [64, 96]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr4=np.arange(15).reshape(3,5)

In [ ]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr4[1:,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
arr_2d[1]  # Indexing 2nd row

array([12, 15, 18])

In [ ]:
arr_2d[:,2] # Indexing 3rd column

array([  3,  18, 128])

In [ ]:
arr_2d[1:,1:]

In [ ]:
arr_2d[1,1]

In [8]:
arr_2d[0:2][0:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [9]:
# Indexing column
arr_2d[:,2]

array([  3,  18, 128])

In [ ]:
arr5=np.arange(20).reshape(5,4)

In [ ]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr5[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [14]:
# 2D array slicing

#Shape (2,2) from top right corner

arr_2d[:2,1:]

array([[ 2,  3],
       [15, 18]])

In [12]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [15]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr >= 4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[:,0]<4

# Happy Learning!